### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by jovi-Li** [linzhiqiang/Aix.RedisStreamMessageBus#1]
RedisMessageBus消费失败,topic:redis:messagebus:BusinessMessageDemo1，groupName:default-group
StackExchange.Redis.RedisCommandException: Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot
   at StackExchange.Redis.ServerSelectionStrategy.Select(Message message) in /_/src/StackExchange.Redis/ServerSelectionStrategy.cs:line 109
   at StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2206
   at StackExchange.Redis.ConnectionMultiplexer.TryPushMessageToBridgeAsync[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2209
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2711
   at StackExchange.Redis.RedisBase.ExecuteAsync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 47
   at StackExchange.Redis.RedisTransaction.ExecuteAsync(CommandFlags flags) in /_/src/StackExchange.Redis/RedisTransaction.cs:line 59
   at Aix.RedisStreamMessageBus.RedisImpl.RedisStorage.EnqueueDealy(JobData jobData, TimeSpan delay) in F:\jovi\gitProjects\Aix.RedisStreamMessageBus\src\Aix.RedisStreamMessageBus\RedisImpl\RedisStorage.cs:line 109
   at Aix.RedisStreamMessageBus.BackgroundProcess.WorkerProcess.Handle(StreamEntry streamEntry, JobData jobData) in F:\jovi\gitProjects\Aix.RedisStreamMessageBus\src\Aix.RedisStreamMessageBus\BackgroundProcess\WorkerProcess.cs:line 162
   at Aix.RedisStreamMessageBus.BackgroundProcess.WorkerProcess.HandleWrap(StreamEntry streamEntry, JobData jobData) in F:\jovi\gitProjects\Aix.RedisStreamMessageBus\src\Aix.RedisStreamMessageBus\BackgroundProcess\WorkerProcess.cs:line 134

**Comment by jovi-Li** [comment]
public async Task<bool> EnqueueDealy(JobData jobData, TimeSpan delay)  这个方法用事物处理，在集群下有这个问题

**Comment by linzhiqiang** [comment]
> public async Task EnqueueDealy(JobData jobData, TimeSpan delay) 这个方法用事物处理，在集群下有这个问题

redis集群不支持事务，只有单个节点支持
